name: lookme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  accordion: ^2.6.0
  auto_scroll_image: ^0.2.9-dev
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  carousel_slider: ^5.0.0
  country_code_picker: ^3.2.0
  dio: ^5.8.0+1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_login: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.17
  get: ^4.7.2
  get_storage: ^2.1.1
  marquee: ^2.3.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  slide_countdown: ^2.0.2
  tab_container: ^3.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/images/category/
    - assets/images/product/
    - assets/images/banner/
    - assets/images/chat/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
    - family : DMSerifDisplay
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Italic.ttf
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-icon.png"  # Path to your app icon image
  adaptive_icon_background: "#FFFFFF"    # (Optional) Background color for Android adaptive icons
  adaptive_icon_foreground: "assets/images/logo-icon.png"  # Foreground for adaptive icons